# Generated by Django 4.1.6 on 2023-02-08 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('car_model', models.CharField(max_length=200)),
                ('car_description', models.TextField(max_length=200)),
                ('date_manufactured', models.DateTimeField(auto_now_add=True)),
                ('car_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECar.carcolor')),
            ],
            options={
                'ordering': ['date_manufactured'],
            },
        ),
    ]
