# Generated by Django 4.1.6 on 2023-02-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, default='imageholder.png', null=True, upload_to='media'),
        ),
    ]
