# Generated by Django 4.1.6 on 2023-02-09 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='image',
            new_name='car_image',
        ),
    ]
