# Generated by Django 4.1.6 on 2023-02-09 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECar', '0002_rename_image_car_car_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_name',
            new_name='CAR_NAME',
        ),
    ]
