# Generated by Django 4.1.6 on 2023-02-09 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECar', '0003_rename_car_name_car_car_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='CAR_NAME',
            new_name='car_name',
        ),
    ]
